title: SECRET CONFESSIONS
author: Ameena
email: ameena@quintype.com
description: > # this means to ignore newlines until "baseurl:"
  zindagi ka falsafa bhi kitna ajeeb hai,shaame kat ti nahi aur saal guzarte jaa rahe hai..

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
